### ISSUE TITLE
Feature request: handle errors with elaborate error messages while building registered classes

### ISSUE THREAD

**Issue by krishna-esrlabs** [AEV/nucleus7#10]
## Actual Behavior
When I start the training I received a `TypeError ` saying that an expected keyword parameter is missing. It took me a while to figure out which of my `n` number of configs has the missing paramter.
### Stacktrace
```
Traceback (most recent call last):
  File "/nas/krishna/ext_repo/nucleus7/bin/nc7-train", line 142, in <module>
    main()
  File "/nas/krishna/ext_repo/nucleus7/bin/nc7-train", line 135, in main
    trainer = build_train(**config_main)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/runs_builder.py", line 114, in build_train
    metrics_config, base_cls=ModelMetric)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/model_builder.py", line 113, in build_model_nucleotides
    base_cls=base_cls, **each_config)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/utils/deprecated.py", line 264, in wrapped
    return function(*args, **config)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/builder_lib.py", line 74, in wrapped
    **object_kwargs)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/builder_lib.py", line 127, in build_registered_object
    obj = cls(**object_kwargs)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/core/base.py", line 63, in __call__
    instance = super().__call__(*args, **kwargs)
TypeError: __init__() missing 1 required keyword-only argument: 'num_classes'
```

## Expected Behavior
It would be great if the class name is mentioned next to the TypeError. Then it will be easier to jump into the right config file and quickly fix it. 
* NOTE: I have a solution and the expected stacktrace will look like below. I will add this in the existing pull request or make a new one.
### Stacktrace
```
Traceback (most recent call last):
  File "/nas/krishna/ext_repo/nucleus7/bin/nc7-train", line 142, in <module>
    main()
  File "/nas/krishna/ext_repo/nucleus7/bin/nc7-train", line 135, in main
    trainer = build_train(**config_main)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/runs_builder.py", line 114, in build_train
    metrics_config, base_cls=ModelMetric)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/model_builder.py", line 113, in build_model_nucleotides
    base_cls=base_cls, **each_config)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/utils/deprecated.py", line 264, in wrapped
    return function(*args, **config)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/builder_lib.py", line 74, in wrapped
    **object_kwargs)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/builders/builder_lib.py", line 127, in build_registered_object
    obj = cls(**object_kwargs)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/core/base.py", line 70, in __call__
    raise type(e)(msg).with_traceback(tb)
  File "/nas/krishna/ext_repo/nucleus7/nucleus7/core/base.py", line 65, in __call__
    instance = super().__call__(*args, **kwargs)
TypeError: SemanticSegmentationMetrics.__init__() missing 1 required keyword-only argument: 'num_classes'
```

**Comment by krishna-esrlabs** [comment]
I am adding a similar feature request here instead of a duplicate.
This time elaborate error messages is required for `data processor`. If I miss one of the expected input keys mapping in the config file for a `data processor`,  it gives a `TypeError` as below
```TypeError: process() missing 1 required keyword-only argument: 'images'```
If there are many data processors it takes a while to figure out which one. Printing the class name can help the users to navigate to the problem location easily.

**Comment by krishna-esrlabs** [comment]
This feature request should also include,
* ModelLoss
* ModelPlugin
* ModelSummary
* PostProcessor
* KPIplugin
* may be few more base classes I might have missed

To be more clear on this feature request, I explain with a `FasterRCNNSecondStagePlugin` example.
I added a new parameter 'x' to the predict function of  `FasterRCNNSecondStagePlugin` and I did not add it to the incoming keys list. So this passes the configuration check that happens before building nucleotides, but it fails during run time as below.

```
File "/nas/krishna/ext_repo/nucleus7/nucleus7/model/plugin.py", line 158, in _call
    predictions = self.predict(**inputs)
TypeError: predict() missing 1 required positional argument: 'x'
```
So, why would someone have a parameter which is not registered in the incoming keys. Developers may not do it intentionally but it can happen because of a typo or forgetfulness or a name change in data fields  which indirectly effects all the dependent plugins

This feature request helps us pointing to the right location of the problem, the expected error message should look like below.
```
File "/nas/krishna/ext_repo/nucleus7/nucleus7/model/plugin.py", line 158, in _call
    predictions = self.predict(**inputs)
TypeError: FasterRCNNSecondStagePlugin.predict() missing 1 required positional argument: 'x'
```
