### ISSUE TITLE
Bug report: Cannot use callbacks as inbound node for KPI

### ISSUE THREAD

**Issue by intcl** [AEV/nucleus7#6]
**Expected behavior:**
You can use callbacks as inbound nodes for kpi nucleotides.

**Actual behavior:**
Gives a KeyError.

  ```
Traceback (most recent call last):
File "/home/cl/git/nucleus7/bin/nc7-infer", line 181, in <module>
    main()
  File "/home/cl/git/nucleus7/bin/nc7-infer", line 164, in main
    inferer = build_infer(**config_main)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/builders/runs_builder.py", line 245, in build_infer
    continue_last=continue_last)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/builders/inferer_builder.py", line 75, in build
    **inferer_config)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/utils/deprecated.py", line 264, in wrapped
    return function(*args, **config)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/builders/builder_lib.py", line 74, in wrapped
    **object_kwargs)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/builders/builder_lib.py", line 129, in build_registered_object
    obj.build()
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/coordinator/inferer.py", line 204, in build
    self._build_callbacks_handler_dna()
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/coordinator/inferer.py", line 484, in _build_callbacks_handler_dna
    incoming_nucleotides=incoming_nucleotides)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/utils/object_utils.py", line 135, in wrapped
    return function(self, *args, **kwargs)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/core/gene_handler.py", line 281, in build_dna
    self._maybe_build_nucleotides_dna(incoming_nucleotides)
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/core/gene_handler.py", line 538, in _maybe_build_nucleotides_dna
    each_nucleotide.inbound_nodes]
  File "/home/cl/miniconda3/envs/nc7/lib/python3.6/site-packages/nucleus7-0.10.0-py3.6.egg/nucleus7/core/gene_handler.py", line 537, in <listcomp>
    for each_inbound_node_name in
KeyError: 'dataset_c'

Process finished with exit code 1
```
dataset_c is the name of a callback

**Steps to reproduce the problem:**
nc7-infer with callback as inbound node for kpi

**Comment by krishna-esrlabs** [comment]
@intcl Did you try using metrics instead of KPI?

**Comment by OleksandrVorobiov** [comment]
ModelMetric is intended to be used only for the training and cannot be used after callbacks.
I will check it and will make a fix for it.
